name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --system

    - name: Lint code
      run: bin/lint

    - name: Run unit tests
      run: bin/tests

    - name: Verify solutions
      run: bin/solutions

    - name: Upload coverage report
      run: coveralls
      env:
        COVERALLS_REPO_TOKEN:  ${{ secrets.COVERALLS_REPO_TOKEN }}
